# 一般选项
general_option:
  # 镶嵌设置
  inlay:
    # 镶嵌类型
    # TITLE_LORE   >> 通过武器上 Lore的标题 来进行镶嵌
    # VACANCY_LORE >> 通过武器上 空缺的Lore 来进行镶嵌
    type: "TITLE_LORE"
    lore:
      title_lore: "&e&l● &7&l&m    ----    &6&l||&e&l武器雕纹&6&l||&7&l&m    ----    &r &e&l●"
      vacancy_lore: "&7[可镶嵌雕纹槽]"
# GUI选项
gui_option:
  # 镶嵌
  inlay_GUI:
    title: "&6&l雕纹镶嵌界面 &e&l>"
  carve_GUI:
    title: "&6&l雕纹雕琢界面 &e&l>"
# 设置物品的类型 (请不要输入方块!)  默认为1.10.2的物品Id
# HEAD ---> 是头部装备的 物品Id
# CHEST ---> 是衣服装备的 物品Id
# LEGS ---> 是护腿装备的 物品Id
# FEET ---> 是鞋子装备的 物品Id
# WEAPON ---> 是手持装备的 物品Id
# ALL ---> 是所有可镶嵌的 物品Id
weapon_option:
  type:
    HEAD:
      - "298:0"
      - "302:0"
      - "306:0"
      - "310:0"
      - "314:0"
    CHEST:
      - "299:0"
      - "303:0"
      - "307:0"
      - "311:0"
      - "315:0"
    LEGS:
      - "300:0"
      - "304:0"
      - "308:0"
      - "312:0"
      - "316:0"
    FEET:
      - "301:0"
      - "305:0"
      - "309:0"
      - "313:0"
      - "317:0"
    WEAPON:
      - "261:0"
      - "267:0"
      - "268:0"
      - "272:0"
      - "276:0"
      - "283:0"
      - "442:0"
      - "256:0"
      - "257:0"
      - "258:0"
      - "269:0"
      - "270:0"
      - "271:0"
      - "273:0"
      - "274:0"
      - "275:0"
      - "277:0"
      - "278:0"
      - "279:0"
      - "284:0"
      - "285:0"
      - "286:0"
      - "290:0"
      - "291:0"
      - "292:0"
      - "293:0"
      - "294:0"
    ALL:
      - "298:0"
      - "302:0"
      - "306:0"
      - "310:0"
      - "314:0"
      - "299:0"
      - "303:0"
      - "307:0"
      - "311:0"
      - "315:0"
      - "300:0"
      - "304:0"
      - "308:0"
      - "312:0"
      - "316:0"
      - "305:0"
      - "309:0"
      - "313:0"
      - "317:0"
      - "261:0"
      - "267:0"
      - "268:0"
      - "272:0"
      - "276:0"
      - "283:0"
      - "442:0"
      - "256:0"
      - "257:0"
      - "258:0"
      - "269:0"
      - "270:0"
      - "271:0"
      - "273:0"
      - "274:0"
      - "275:0"
      - "277:0"
      - "278:0"
      - "279:0"
      - "284:0"
      - "285:0"
      - "286:0"
      - "290:0"
      - "291:0"
      - "292:0"
      - "293:0"
      - "294:0"