name: Glyph
main: cc.deepinmc.glyph.Entry
version: 2.0.0
author: DeepinMC
commands:
  glyph:
    aliases: [diaowen, dw, dk]
    description: "Glyph's Main command"
permission:
  glyph.get:
    default: op
  glyph.open:
    default: op
