name: Glyph
main: cc.deepinmc.glyph.Entry
version: 2.0.0
author: DeepinMC
commands:
  glyph:
    aliase: [diaowen, dw, dk]
    description: "Main command"
permissions:
  glyph.use:
    default: true
  glyph.open:
    default: op
